-- AlterTable
ALTER TABLE `user` ADD COLUMN `roleId` INTEGER NOT NULL DEFAULT 3;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `Role`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
